### PR TITLE
Add user filter in teaming page

### PR DESCRIPTION
**Pull request by Cronobow**
What & Why?
---
1. Add user filter in teaming page

How was it tested?
---
localhost

cc @spreered @eggyy1224

### CODE REVIEW

**Comment by Cronobow** [comment]
先不要 merge

**Comment by Cronobow** [comment]
@spreered @eggyy1224 可以了
感謝 @spreered 出手

**Comment by spreered** [comment]
LGTM

**Comment by eggyy1224** [comment]
ＬＧＴＭ

**Pull request merged**
