### PR TITLE
Add side bar

### PR DESCRIPTION
**Pull request by Cronobow**
What & Why?
---
1. add sidebar
2. add admin sidebar
3. ~~navbar dropdown still have some problems~~ fixed

How was it tested?
---
localhost

cc @spreered @eggyy1224

### CODE REVIEW

**Comment by eggyy1224** [comment]
@Cronobow 拜託解一下衝突摟

**Comment by Cronobow** [comment]
@eggyy1224 解好了

**Comment by eggyy1224** [comment]
LGTM

**Comment by Cronobow** [comment]
Navbar 問題修好了

**Pull request merged**
